-- ==========================================
-- 1. Insert Customer Records (Oracle Compatible)
-- ==========================================
INSERT INTO CUSTOMER (CustomerName, Address, Phone) VALUES ('Tejas Mahamuni', 'Ahilyanagar, Maharashtra', '9322188608');
INSERT INTO CUSTOMER (CustomerName, Address, Phone) VALUES ('Rushikesh Shinde', 'Ahilyanagar, Maharashtra', '8180917274');
INSERT INTO CUSTOMER (CustomerName, Address, Phone) VALUES ('Aarav Sharma', 'Mumbai, Maharashtra', '9823011234');
INSERT INTO CUSTOMER (CustomerName, Address, Phone) VALUES ('Priya Patel', 'Ahmedabad, Gujarat', '9176543210');
INSERT INTO CUSTOMER (CustomerName, Address, Phone) VALUES ('Rohan Das', 'Kolkata, West Bengal', '9830098765');
INSERT INTO CUSTOMER (CustomerName, Address, Phone) VALUES ('Ananya Reddy', 'Hyderabad, Telangana', '9440123456');
INSERT INTO CUSTOMER (CustomerName, Address, Phone) VALUES ('Vikram Singh', 'Jaipur, Rajasthan', '9610234567');
INSERT INTO CUSTOMER (CustomerName, Address, Phone) VALUES ('Sneha Iyer', 'Chennai, Tamil Nadu', '9840567890');
INSERT INTO CUSTOMER (CustomerName, Address, Phone) VALUES ('Arjun Verma', 'New Delhi, Delhi', '9810012345');
INSERT INTO CUSTOMER (CustomerName, Address, Phone) VALUES ('Kavita Rao', 'Bengaluru, Karnataka', '9900123456');
INSERT INTO CUSTOMER (CustomerName, Address, Phone) VALUES ('Rahul Joshi', 'Pune, Maharashtra', '9371054321');
INSERT INTO CUSTOMER (CustomerName, Address, Phone) VALUES ('Meera Nair', 'Kochi, Kerala', '9447012345');
INSERT INTO CUSTOMER (CustomerName, Address, Phone) VALUES ('Amit Mishra', 'Lucknow, Uttar Pradesh', '9415098765');
COMMIT;


-- ==========================================
-- 2. Insert Vehicle Records
-- ==========================================
INSERT INTO VEHICLE (VEHICLENUMBER, VEHICLETYPE, CAPACITY) VALUES ('MH12AB4821', 'Truck', 5000);
INSERT INTO VEHICLE (VEHICLENUMBER, VEHICLETYPE, CAPACITY) VALUES ('DL03CY8912', 'Van', 1500);
INSERT INTO VEHICLE (VEHICLENUMBER, VEHICLETYPE, CAPACITY) VALUES ('KA51MJ2345', 'Mini Truck', 2500);
INSERT INTO VEHICLE (VEHICLENUMBER, VEHICLETYPE, CAPACITY) VALUES ('TN22RS7012', 'Tempo', 1200);
INSERT INTO VEHICLE (VEHICLENUMBER, VEHICLETYPE, CAPACITY) VALUES ('GJ01ZU5567', 'Container', 12000);
INSERT INTO VEHICLE (VEHICLENUMBER, VEHICLETYPE, CAPACITY) VALUES ('HR26BQ9034', 'Truck', 7000);
INSERT INTO VEHICLE (VEHICLENUMBER, VEHICLETYPE, CAPACITY) VALUES ('UP32HA1122', 'Van', 1800);
INSERT INTO VEHICLE (VEHICLENUMBER, VEHICLETYPE, CAPACITY) VALUES ('WB02KL6789', 'Mini Truck', 3000);
INSERT INTO VEHICLE (VEHICLENUMBER, VEHICLETYPE, CAPACITY) VALUES ('TS09EQ4531', 'Tempo', 1000);
INSERT INTO VEHICLE (VEHICLENUMBER, VEHICLETYPE, CAPACITY) VALUES ('MH12RS9988', 'Container', 15000);
INSERT INTO VEHICLE (VEHICLENUMBER, VEHICLETYPE, CAPACITY) VALUES ('KA03NV3412', 'Truck', 6000);
INSERT INTO VEHICLE (VEHICLENUMBER, VEHICLETYPE, CAPACITY) VALUES ('DL01XY4061', 'Van', 2000);
INSERT INTO VEHICLE (VEHICLENUMBER, VEHICLETYPE, CAPACITY) VALUES ('TN07JW8254', 'Mini Truck', 3500);
INSERT INTO VEHICLE (VEHICLENUMBER, VEHICLETYPE, CAPACITY) VALUES ('UP16TX2399', 'Container', 18000);
INSERT INTO VEHICLE (VEHICLENUMBER, VEHICLETYPE, CAPACITY) VALUES ('GJ05BC6112', 'Tempo', 900);
COMMIT;


-- ==========================================
-- 3. Insert Driver Records (Oracle Compatible)
-- ==========================================
INSERT INTO DRIVER (DRIVERNAME, PHONE, LICENSENUMBER) VALUES ('Ramesh Shinde', '9822145678', 'MH1620210045612');
INSERT INTO DRIVER (DRIVERNAME, PHONE, LICENSENUMBER) VALUES ('Sunita Sharma', '9158432109', 'DL0320190089123');
INSERT INTO DRIVER (DRIVERNAME, PHONE, LICENSENUMBER) VALUES ('Aniket Patil', '7709564321', 'MH1220180023456');
INSERT INTO DRIVER (DRIVERNAME, PHONE, LICENSENUMBER) VALUES ('Deepak Verma', '8888123456', 'UP3220200055678');
INSERT INTO DRIVER (DRIVERNAME, PHONE, LICENSENUMBER) VALUES ('Rajesh Kumar', '9422078912', 'HR2620170090341');
INSERT INTO DRIVER (DRIVERNAME, PHONE, LICENSENUMBER) VALUES ('Suresh Deshmukh', '9325112233', 'MH1420220011223');
INSERT INTO DRIVER (DRIVERNAME, PHONE, LICENSENUMBER) VALUES ('Pooja Joshi', '9637456789', 'KA0320150067890');
INSERT INTO DRIVER (DRIVERNAME, PHONE, LICENSENUMBER) VALUES ('Manoj Tiwari', '9923887766', 'WB0220160045312');
INSERT INTO DRIVER (DRIVERNAME, PHONE, LICENSENUMBER) VALUES ('Vikram Jadhav', '7507123456', 'MH1620230099881');
INSERT INTO DRIVER (DRIVERNAME, PHONE, LICENSENUMBER) VALUES ('Karan Singh', '8411998877', 'GJ0120210034123');
COMMIT;


-- ==========================================
-- 4. Insert Dispatch Order Records (Oracle Compatible)
-- ==========================================
INSERT INTO DISPATCHORDER (CUSTOMERID, SOURCE, DESTINATION) VALUES (1, 'Mumbai, Maharashtra', 'Ahilyanagar');
INSERT INTO DISPATCHORDER (CUSTOMERID, SOURCE, DESTINATION) VALUES (2, 'Ahmedabad, Gujarat', 'Mumbai, Maharashtra');
INSERT INTO DISPATCHORDER (CUSTOMERID, SOURCE, DESTINATION) VALUES (3, 'Kolkata, West Bengal', 'Pune, Maharashtra');
INSERT INTO DISPATCHORDER (CUSTOMERID, SOURCE, DESTINATION) VALUES (4, 'Hyderabad, Telangana', 'Bengaluru, Karnataka');
INSERT INTO DISPATCHORDER (CUSTOMERID, SOURCE, DESTINATION) VALUES (5, 'Jaipur, Rajasthan', 'New Delhi, Delhi');
COMMIT;


-- ==========================================
-- 5. Insert Access Control Users
-- ==========================================
INSERT INTO USERS (USERNAME, PASSWORD, ROLE) VALUES ('admin', 'admin123', 'ADMIN');
INSERT INTO USERS (USERNAME, PASSWORD, ROLE) VALUES ('dispatcher1', 'disp123', 'DISPATCHER');
INSERT INTO USERS (USERNAME, PASSWORD, ROLE) VALUES ('driver1', 'driver123', 'DRIVER');
COMMIT;


-- ==========================================
-- 6. Insert LOV Configuration Parameters
-- ==========================================
INSERT INTO LOV_MASTER (LOV_TYPE, LOV_VALUE, STATUS) VALUES ('VehicleType', 'Truck', 'ACTIVE');
INSERT INTO LOV_MASTER (LOV_TYPE, LOV_VALUE, STATUS) VALUES ('VehicleType', 'Mini Truck', 'ACTIVE');
INSERT INTO LOV_MASTER (LOV_TYPE, LOV_VALUE, STATUS) VALUES ('VehicleType', 'Van', 'ACTIVE');
INSERT INTO LOV_MASTER (LOV_TYPE, LOV_VALUE, STATUS) VALUES ('VehicleType', 'Container', 'ACTIVE');
INSERT INTO LOV_MASTER (LOV_TYPE, LOV_VALUE, STATUS) VALUES ('VehicleType', 'Tempo', 'ACTIVE');

-- Dispatch Order Status LOVs
INSERT INTO LOV_MASTER (LOV_TYPE, LOV_VALUE, STATUS) VALUES ('DispatchOrderStatus', 'Pending', 'ACTIVE');
INSERT INTO LOV_MASTER (LOV_TYPE, LOV_VALUE, STATUS) VALUES ('DispatchOrderStatus', 'In Progress', 'ACTIVE');
INSERT INTO LOV_MASTER (LOV_TYPE, LOV_VALUE, STATUS) VALUES ('DispatchOrderStatus', 'Completed', 'ACTIVE');
INSERT INTO LOV_MASTER (LOV_TYPE, LOV_VALUE, STATUS) VALUES ('DispatchOrderStatus', 'Cancelled', 'ACTIVE');
INSERT INTO LOV_MASTER (LOV_TYPE, LOV_VALUE, STATUS) VALUES ('DispatchOrderStatus', 'In Transit', 'ACTIVE');
COMMIT;

